### ISSUE TITLE
linop licensing question

### ISSUE THREAD

**Issue by grlee77** [PythonOptimizers/pykrylov#37]
I see that pykrylov is licensed as LGPL v2, however there is a fork of the `linop` module by @ghisvail at https://github.com/ghisvail/linop that seems to be BSD licensed.

Would it be okay to merge some the Hermitian linop code that has since been added here into that `linop` module while maintaining a BSD license?  I ask because I know it is not possible to just relicense a LGPL project as BSD arbitrarily.  If so, I can make a PR over at https://github.com/ghisvail/linop to update it to contain more recent functionality added here.

The end goal for me would be to be able to use the linear operator functionality developed here in projects that are currently BSD-licensed.

**Comment by dpo** [comment]
Could you indicate what kind of projects the BSD code would be used for?

**Comment by grlee77** [comment]
I would be using it for nonprofit research related to image reconstruction for magnetic resonance imaging.  I would wrap operators for things like the discrete wavelet transform, fourier transform, etc.  I would prefer to eventually release code using a BSD license rather than LGPL in order to be less restrictive in the license terms.

As you are probably aware, the BSD license is more permissive and doesn't require modified versions of the code to also be made openly available.  Someone could potentially modify the software for commercial use in the future if that is a concern.

**Comment by dpo** [comment]
I think it's ok to relicense parts of the package provided it's clearly indicated that the mother repository is here and that I'm the original author.

**Comment by grlee77** [comment]
sure.  thanks!

**Comment by ghisvail** [comment]
Sorry for my late reply. Indeed both @dpo and myself agreed back in the day to extract the `linop` package from `pykrylov` and relicense it under BSD.

On a side note, LGPL is a bad idea because the concept of **linkage** is ambiguous for a high-level language such as Python. This is likely to scare away any legal department. If copyleft is that desirable, you might want to consider relicensing from LGPL to MPL-2 since the terms are much more straightforward to comply in case of a Python library.

> I think it's ok to relicense parts of the package provided it's clearly indicated that the mother repository is here and that I'm the original author.

Which is the case for `linop`. @grlee77, feel free to send me any PR related to the features you'd like merged to `linop` in the future.

Cheers,
Ghis
